---
version: "3.2"
services:

  redis:
    networks:
      - redis
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  redis-commander:
    networks:
      - redis
    image: "rediscommander/redis-commander"
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST="redis"
      - REDIS_PORT="6379"
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
networks:
  redis:
